# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: IdealYard
subtitle: Valar Dohaeris.
description: ä½ å¦‚ä»Šçš„æ°”è´¨é‡Œï¼Œè—ç€ä½ èµ°è¿‡çš„è·¯ã€è¯»è¿‡çš„ä¹¦å’Œçˆ±è¿‡çš„äººã€‚
slogan: å°±å‘½è¿è€Œè¨€ï¼Œä¼‘è®ºå…¬é“ã€‚
keywords: Think Whisper Share
author: SanTu
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://masantu.github.io
root: /
#permalink: :year/:month/:day/:title/
permalink: post/:year-:month-:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#ä¸»é¢˜æ›´æ”¹
#theme: next
theme: santu

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/masantu/masantu.github.io.git

  branch: master
# Local Search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# ä»£ç é«˜äº®æ–¹æ¡ˆhttps://github.com/ele828/hexo-prism-plugin
#prism_plugin:
#  mode: 'preprocess'    # realtime/preprocess
#  theme: 'hopscotch'
#  line_number: true    # default false

# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: false
  smartLists: true
  smartypants: true

# encrypt plugin
# https://github.com/MikeCoder/hexo-blog-encrypt
encrypt:
  enable: true
  abstract: Here's something encrypted, password is required to continue reading.
  message: Hey, password is required here.

admin:
  deployCommand: 'hexo-deploy.bat'
# https://github.com/MoePlayer/hexo-tag-aplayer/blob/master/docs/README-zh_cn.md
aplayer:
  meting: true
# é“¾æ¥æ·»åŠ  nofollow
nofollow:
  enable: true
  field: site
  exclude:
    - 'www.masantu.com'
    - 'blog.masantu.com'
    - 'masantu.com'

douban:
  user: imoyao
  builtin: false
  book:
    title: 'é˜…è¯»ï¼Œä¸å¦ä¸€ä¸ªçµé­‚è¿›è¡Œå¯¹è¯'
    quote: 'æ¥¼ä¸‹ä¸€ä¸ªç”·äººç—…å¾—è¦æ­»ï¼Œé‚£é—´éš”å£çš„ä¸€å®¶å”±ç€ç•™å£°æœºï¼Œå¯¹é¢æ˜¯å¼„å­©å­ã€‚æ¥¼ä¸Šæœ‰ä¸¤äººç‹‚ç¬‘ï¼Œè¿˜æœ‰æ‰“ç‰Œå£°ã€‚æ²³ä¸­çš„èˆ¹ä¸Šæœ‰å¥³äººå“­ç€å¥¹æ­»å»çš„æ¯äº²ã€‚äººç±»çš„æ‚²æ¬¢å¹¶ä¸ç›¸é€šï¼Œæˆ‘åªè§‰å¾—ä»–ä»¬åµé—¹ã€‚<div align = right> â€”â€”é²è¿…Â·ã€Šè€Œå·²é›†Â·å°æ‚æ„Ÿã€‹ </div>'
  movie:
    title: 'ç”µå½±ï¼Œæ¢ç´¢ç”Ÿæ´»åœ¨åˆ«å¤„çš„å¯èƒ½'
    quote: 'ä½ åªæ˜¯ä¸ªå­©å­ï¼Œä½ æ ¹æœ¬ä¸æ™“å¾—ä½ åœ¨è¯´ä»€ä¹ˆã€‚<br>
æ‰€ä»¥é—®ä½ è‰ºæœ¯,ä½ å¯èƒ½ä¼šæå‡ºè‰ºæœ¯ä¹¦ç±ä¸­çš„ç²—æµ…è®ºè°ƒã€‚æœ‰å…³ç±³å¼€æœ—åŸºç½—ï¼Œä½ çŸ¥é“å¾ˆå¤šï¼Œä»–çš„æ»¡è…”æ”¿æ²»çƒ­æƒ…ï¼Œä¸æ•™çš‡ç›¸äº¤è«é€†ï¼Œè€½äºæ€§çˆ±ï¼Œä½ å¯¹ä»–å¾ˆæ¸…æ¥šå§ï¼Ÿä½†ä½ è¿è¥¿æ–¯æ±€æ•™å ‚çš„æ°”å‘³ä¹Ÿä¸çŸ¥é“å§ï¼Ÿä½ æ²¡è¯•è¿‡ç«™åœ¨é‚£å„¿ï¼Œæ˜‚é¦–çœºæœ›å¤©èŠ±æ¿ä¸Šçš„åç”»å§ï¼Ÿè‚¯å®šæœªè§è¿‡å§ï¼Ÿ<br>
å¦‚æœæˆ‘é—®å…³äºå¥³äººçš„äº‹ï¼Œä½ å¤§å¯ä»¥å‘æˆ‘å¦‚æ•°å®¶çï¼Œä½ å¯èƒ½ä¸Šè¿‡å‡ æ¬¡åºŠï¼Œä½†ä½ æ²¡æ³•è¯´å‡ºåœ¨å¥³äººèº«æ—é†’æ¥æ—¶ï¼Œé‚£ä»½å†…å¿ƒçœŸæ­£çš„å–œæ‚¦ã€‚<br>
ä½ å¹´è½»å½ªæ‚ï¼Œæˆ‘å¦‚æœå’Œä½ è°ˆè®ºæˆ˜äº‰ï¼Œä½ ä¼šå‘æˆ‘å¤§æŠ›èå£«æ¯”äºšï¼Œæœ—è¯µâ€œå…±èµ´æˆ˜åœºï¼Œäº²çˆ±çš„æœ‹å‹â€ï¼Œä½†ä½ ä»æœªäº²ä¸´æˆ˜é˜µï¼Œæœªè¯•è¿‡æŠŠæŒšå‹çš„å¤´æ‹¥å…¥æ€€é‡Œï¼Œçœ‹ç€ä»–å¸ç€æœ€åä¸€å£æ°”ï¼Œå‡æœ›ç€ä½ ï¼Œå‘ä½ æ±‚åŠ©ã€‚<br>
æˆ‘é—®ä½ ä½•ä¸ºçˆ±æƒ…ï¼Œä½ å¯èƒ½åªä¼šåŸé£å¼„æœˆï¼Œç»™æˆ‘èƒŒåå››è¡Œè¯—ï¼Œä½†ä½ æœªè¯•è¿‡å…¨æƒ…æŠ•å…¥çœŸå¿ƒå€¾å€’ï¼Œå››ç›®äº¤æŠ•æ—¶å½¼æ­¤äº†è§£å¯¹æ–¹çš„å¿ƒï¼Œå¥½æ¯”ä¸Šå¸å®‰æ’å¤©ä½¿ä¸‹å‡¡åªçŒ®ç»™ä½ ï¼ŒæŠŠä½ ä»åœ°ç‹±æ·±æ¸Šæ‹¯æ•‘å‡ºæ¥ï¼Œå¯¹å¥¹ç™¾èˆ¬å…³æ€€çš„æ„Ÿå—ä½ ä¹Ÿä»æœªè¯•è¿‡ï¼Œä½ ä»æœªè¯•è¿‡å¯¹å¥¹çš„æƒ…æ·±æ¬¾æ¬¾çŸ¢å¿—å®å®ˆï¼Œæ˜çŸ¥å¥¹æ‚£äº†ç»ç—‡ä¹Ÿåœ¨æ‰€ä¸æƒœï¼Œä½ ä»æœªå°è¯•è¿‡ç—›å¤±æŒšçˆ±çš„æ„Ÿå—â€¦â€¦<div align = right> â€”â€”ã€Šå¿ƒçµæ•æ‰‹ã€‹</div>'
#  game:
#    title: 'This is my game title'
#    quote: 'This is my game quote'
  timeout: 86400000
comments: true
plugins:
#      -----------------Valine-----------------
#   Valine comment system. https://valine.js.org
  valine:
    enabled: true # if you want use valine, please set this value to true
    appId:  jjycPyl8ahtrP7nTFane9Nbx-MdYXbMMI # your leancloud appId
    appKey:  xENmWhVnYTxpn9y2DE6fVarm # your leancloud appKey
    notify: false # Mail notify
    verify: false # Verify code
    avatar: monsterid # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
    placeholder: Enjoy yourself!ğŸ˜˜ # Comment Box placeholder
    guest_info: nick,mail,link # Comment header info
    pageSize: 10 # comment list page size
    highlight: false
    recordIP: true
    visitor: true
    lang: en

#https://github:com/lzane/hexo-light-gallery
lightgallery:
    # if you don't specify the css or js source, the default cdn will be used.
    # css: # css source url
    # js: #js source url
    # sorry that I can not find any cdn hosting following plugins,
    # please self-host the plugin js and add url here
    # plugins:
        # lg-thumbnail:
        # lg-zoom:
        # lg-autoplay:
        # lg-fullscreen:
        # lg-pager:
